### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by laijackylai** [kylebarron/snap-to-tin#46]
From the screenshot below
Setting `'allowSyntheticDefaultImports'` flag to be `true` in [tsconfig.json](https://github.com/kylebarron/snap-to-tin/blob/master/tsconfig.json) resolevd the problem and the module can be loaded successfully
<img width="832" alt="Screenshot 2022-03-19 at 12 54 40 AM" src="https://user-images.githubusercontent.com/66239914/159048119-9f45da36-d302-4ad2-9186-8a5a8c3bf97a.png">
Seems to be related to a library called flatbush or might it be other problems?

Also, I must specify `import SnapFeatures from '@kylebarron/snap-to-tin/src/index.ts'` in order to import the module which is different from all "normal" modules.
I'm not familiar with modules creation so please don't mind my stupid question.

Thanks a lot

**Comment by kylebarron** [comment]
Part of the issue here is that I didn't understand JS bundling or TS super well two years ago.

> Also, I must specify `import SnapFeatures from '@kylebarron/snap-to-tin/src/index.ts'` in order to import the module which is different from all "normal" modules.

One issue is that the NPM package inadvertently wasn't including the `dist/` or `lib/` folders. So you should I think now be able to import the package normally with `0.2.1` that I just published. Or I'd assume you could import the `index.ts` as you do above without any issues if you're working in a TS project.

I haven't seen the error about `allowSyntheticDefaultImports` before. If it still happens with `0.2.1` you can make a PR to update this project's tsconfig

**Comment by laijackylai** [comment]
The error is solved, I can import the library normally.
Thank you very much.
